### ISSUE TITLE
Julian Dates option for Plot Measurement downloads

### ISSUE THREAD

**Issue by slin63** [slin63/django_NelsonDB#103]

**Comment by smideros** [comment]
Hi slin63, I don't think this is fixed. 
Or the fix caused trouble.
If from the experiments page you select the "Combined plot and measurement download" you get a file where there are two columns: D and T. The first one is named time of measurement_julian and it only says poor formatting...
Not sure what is going on.
[16CM_plot_measurements.xlsx](https://github.com/slin63/django_NelsonDB/files/642708/16CM_plot_measurements.xlsx)
