### ISSUE TITLE
Field Book issues

### ISSUE THREAD

**Issue by slin63** [slin63/django_NelsonDB#62]
##### Field Book is nice but is missing some things:
- [x] Experiment info needs to be manually added to .csv outputs
- [x] Prevent duplicate measurements from being added
- [x] Old handheld needs to be updated with new plot info

**Comment by tjamann** [comment]
Field book is also the name of the software used to collect data in the field. We should use a different name to refer to the database functionality- maybe field mapper?

**Comment by tjamann** [comment]
Can we add into the instructions that users should enter their db id as their first name before collecting data, not the full name as the prompted by the app

**Comment by slin63** [comment]
Done
