### ISSUE TITLE
Help page for data input

### ISSUE THREAD

**Issue by slin63** [slin63/django_NelsonDB#76]
- [x] Plot info page
  - [x] Add other pollination types to `Pollination Type` field
- [x] Stock info page
- [x] Seed Protocol Page
- [x] Measurement page
- [x] IsolateStock info page
  - [x] Update to remove `Isolate` fields
  - [x] Add a `required` column

**Comment by tjamann** [comment]
Do we need an info site or something on the website that will serve as a guide?
